language: php

php: 
  - '5.6'
  - '7.1'

env:
  global:
    - "FTP_USER=labsroom"
    - "FTP_PASSWORD=bismillah"

after_success:
  "curl -T praktek-1/index.php -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com"